spring.application.name=payment-service
#==========================================
# SERVER CONFIGURATION
# ==========================================
server.port=8085
# ==========================================
# ORACLE DATABASE CONFIGURATION
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=PAYMENT_SERVICE
spring.datasource.password=Payment123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# ==========================================
# JPA / HIBERNATE CONFIGURATION
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true